### ISSUE TITLE
No problem statement in Problem Text file

### ISSUE THREAD

**Issue by jgendron** [jgendron/boozonians#2]
Need a writeup in the Problem Text file to include the problem statement...

**Comment by KLadBAH** [comment]
I will give it a shot

**Comment by jgendron** [comment]
Jordan had some good language that inspired the shift. I thought it would
be good to be good to get his prose on it...

On Sunday, June 12, 2016, KLadBAH notifications@github.com wrote:

> I will give it a shot
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jgendron/boozonians/issues/2#issuecomment-225452233,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG6kC_o4NtStS0-Y3xKUcUlF3X-y4HOJks5qLE6VgaJpZM4Izc8M
> .

## 

http://www.linkedin.com/in/jaygendron
